Force Rebuild

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -59,35 +59,35 @@ jobs:
           
           curl -s -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD"
 
-  notify:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Wait for 2 Minutes with Countdown
-        run: |
-          for i in {120..1}; do
-            echo "⏳ Waiting... $i seconds remaining"
-            sleep 1
-          done
-
-      - name: Dispatch to Sub Projects
-        env:
-          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
-        run: |
-          REPOS=("techroy23/Docker-Peer2Profit" "techroy23/Docker-Wipter" "techroy23/Docker-UrNetwork" "techroy23/Docker-EarnApp" "techroy23/Docker-Chrome")
-
-          for REPO in "${REPOS[@]}"; do
-            echo "🔄 Sending dispatch to $REPO..."
-            RESPONSE=$(curl -s -X POST \
-              -H "Authorization: token $GHCR_TOKEN" \
-              -H "Accept: application/vnd.github.v3+json" \
-              https://api.github.com/repos/$REPO/actions/workflows/docker-publish.yml/dispatches \
-              -d '{"ref":"main"}')
-
-            echo "✅ Response from GitHub: $RESPONSE"
-
-            if [[ "$RESPONSE" == *"Bad credentials"* ]]; then
-              echo "❌ Error: Invalid GitHub token!"
-              exit 1
-            fi
-          done
+#  notify:
+#    needs: build
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Wait for 2 Minutes with Countdown
+#        run: |
+#          for i in {120..1}; do
+#            echo "⏳ Waiting... $i seconds remaining"
+#            sleep 1
+#          done
+#
+#      - name: Dispatch to Sub Projects
+#        env:
+#          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
+#        run: |
+#          REPOS=("techroy23/Docker-Peer2Profit" "techroy23/Docker-Wipter" "techroy23/Docker-UrNetwork" "techroy23/Docker-EarnApp" "techroy23/Docker-Chrome")##
+#
+#          for REPO in "${REPOS[@]}"; do
+#            echo "🔄 Sending dispatch to $REPO..."
+#            RESPONSE=$(curl -s -X POST \
+#              -H "Authorization: token $GHCR_TOKEN" \
+#              -H "Accept: application/vnd.github.v3+json" \
+#              https://api.github.com/repos/$REPO/actions/workflows/docker-publish.yml/dispatches \
+#              -d '{"ref":"main"}')
+#
+#            echo "✅ Response from GitHub: $RESPONSE"
+#
+#            if [[ "$RESPONSE" == *"Bad credentials"* ]]; then
+#              echo "❌ Error: Invalid GitHub token!"
+#              exit 1
+#            fi
+#          done
